vich_uploader:
    db_driver: orm

    mappings:
        user_image:
            uri_prefix: /images/user
            upload_destination: '%kernel.project_dir%/public/images/user'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        post_image:
            uri_prefix: /images/post
            upload_destination: '%kernel.project_dir%/public/images/post'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer